[package]
name = "aztec-net-contracts_test"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v5.2.0", directory="aztec" }
aztec-net-contracts_contract = { path = "../aztec-net-contracts_contract" }
